name: LowLighter Metrics
on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Genrate Metrics
        uses: lowlighter/metrics@master
        with:
          filename: assets/SVGS/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Base
          base: header, activity, community, repositories
          plugin_lines: yes
          plugin_traffic: yes
          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          # Issues and PullRequests
          plugin_followup: yes
          plugin_followup_indepth: yes
          # Activity Charts
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Calcutta
          # GitHub Skyline
          plugin_skyline: yes
          plugin_skyline_year: 2020
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1